# Generated by Django 5.2.6 on 2025-10-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
