# Generated by Django 5.2.6 on 2025-10-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accessbox',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
