# Generated by Django 5.2.6 on 2025-10-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile_accessbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
