# Generated by Django 5.2.6 on 2025-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_studymaterial_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
